# ═══════════════════════════════════════════════════════
# TeleKart — Languages
# Supported: english, hindi, telugu, kannada, tamil, malayalam
# ═══════════════════════════════════════════════════════

STRINGS = {

    # ─────────────────────────────
    # ENGLISH
    # ─────────────────────────────
    "english": {
        "welcome":                   "🙏 *Welcome to {shop_name}!*",
        "browse":                    "🛍 Browse Products",
        "cart":                      "🛒 My Cart",
        "my_orders":                 "📦 My Orders",
        "about":                     "ℹ️ About",
        "contact":                   "📞 Contact",
        "empty_cart":                "Your cart is empty.",
        "added_to_cart":             "✅ {product_name} added to cart!",
        "cart_summary":              "🛒 *Your Cart:*\n\n{items}\n\n*Total: ₹{total}*",
        "checkout":                  "✅ Checkout",
        "clear_cart":                "🗑 Clear Cart",
        "cart_cleared":              "🗑 Cart cleared!",
        "enter_address":             "📍 *Step 1 of 3* — Delivery address:\n\n_Example: Flat 203, Green Apts, Kondapur_",
        "enter_phone":               "📱 *Step 2 of 3* — Your phone number:",
        "enter_delivery_date":       "🗓 *Step 3 of 3* — When do you want delivery?\n\n_Type: Today / Tomorrow / Jaldi / 1 Mar_",
        "invalid_address":           "⚠️ Please enter a complete address (min 15 characters):",
        "invalid_phone":             "⚠️ Please enter a valid Indian mobile number (starts with 6-9):",
        "invalid_date":              "⚠️ Didn't get that. Try: *Today*, *Tomorrow*, *Jaldi*, or a date like *1 Mar*",
        "order_summary":             "📋 *Order Summary*\n\n{items}\n*Total: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 Delivery: {delivery_date}",
        "confirm_order":             "✅ Confirm & Pay",
        "pay_upi":                   "📲 Pay via UPI / GPay / PhonePe",
        "pay_cod":                   "💵 Cash on Delivery (COD)",
        "order_placed":              "🎉 *Order Placed!*\n\nYour order *{order_ref}* has been received.",
        "cod_instructions":          "💵 *Cash on Delivery*\n\nPlease keep *₹{total}* ready at delivery.",
        "no_products":               "🛍 No products available right now. Check back soon!",
        "shop_not_found":            "❌ Shop not found. Please use a valid shop link.",
        "shop_closed":               "🕐 *{shop_name}* is currently closed.\n\nOpen: *{open_time}* to *{close_time}* IST",
        "use_shop_link":             "Please use a shop link to get started.",
        "order_confirmed_customer":  "🎉 *Your order is confirmed!*\n\nWe're preparing it for your requested date.",
        "order_cancelled_customer":  "❌ *Your order has been cancelled.*\n\nContact the shop for more info.",
        "order_delivered_customer":  "🎉 *Your order has been delivered!*\n\nThank you for ordering!",
        "my_orders_header":          "📦 *Your Orders:*\n\n",
        "no_orders":                 "📦 *No orders yet!*\n\nPlace your first order 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ Cancel Checkout",
        "checkout_cancelled":        "❌ Checkout cancelled.\n\nYour cart is saved!",
        "back_to_menu":              "🏠 Menu",
        "back_to_cart":              "🛒 Back to Cart",
        "start_shopping":            "🛍 Start Shopping",
        "rate_product":              "How was: *{product_name}*?\nTap to rate 👇",
        "review_thanks":             "Thank you for your rating! 🙏",
        "choose_language":           "🌐 *Choose your language:*",
        "language_set":              "✅ Language set to English!",
        "session_expired":           "⚠️ Session expired. Please open your shop link again.",
        "out_of_stock":              "❌ Out of stock.",
        "only_left":                 "⚠️ Only {stock} left!",
        "notify_me":                 "🔔 Notify Me",
        "notify_contact":            "Contact the shop to be notified 📞: {contact}",
        "reorder_ready":             "🔄 *Reorder Ready!*",
        "order_more":                "🛍 Order More",
        "track_order":               "📦 Track Order",
        "welcome_back_cart":         "👋 Welcome back! You have *{n} {word}* waiting in your cart 🛒",
        "change_language":           "🌐 Language",
    },

    # ─────────────────────────────
    # HINDI — हिंदी
    # ─────────────────────────────
    "hindi": {
        "welcome":                   "🙏 *{shop_name}* में आपका स्वागत है!",
        "browse":                    "🛍 प्रोडक्ट देखें",
        "cart":                      "🛒 मेरी कार्ट",
        "my_orders":                 "📦 मेरे ऑर्डर",
        "about":                     "ℹ️ शॉप के बारे में",
        "contact":                   "📞 संपर्क करें",
        "empty_cart":                "आपकी कार्ट खाली है।",
        "added_to_cart":             "✅ {product_name} कार्ट में जोड़ा गया!",
        "cart_summary":              "🛒 *आपकी कार्ट:*\n\n{items}\n\n*कुल: ₹{total}*",
        "checkout":                  "✅ चेकआउट",
        "clear_cart":                "🗑 कार्ट साफ़ करें",
        "cart_cleared":              "🗑 कार्ट साफ़ हो गई!",
        "enter_address":             "📍 *चरण 1/3* — डिलीवरी का पता लिखें:\n\n_उदाहरण: फ्लैट 203, ग्रीन अपार्टमेंट, कोंडापुर_",
        "enter_phone":               "📱 *चरण 2/3* — अपना फोन नंबर लिखें:",
        "enter_delivery_date":       "🗓 *चरण 3/3* — डिलीवरी कब चाहिए?\n\n_लिखें: आज / कल / जल्दी / 1 मार्च_",
        "invalid_address":           "⚠️ कृपया पूरा पता लिखें (कम से कम 15 अक्षर):",
        "invalid_phone":             "⚠️ कृपया सही भारतीय मोबाइल नंबर दर्ज करें (6-9 से शुरू):",
        "invalid_date":              "⚠️ यह तारीख बीत चुकी है। भविष्य की तारीख दर्ज करें:",
        "order_summary":             "📋 *ऑर्डर सारांश*\n\n{items}\n*कुल: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 डिलीवरी: {delivery_date}",
        "confirm_order":             "✅ ऑर्डर कन्फर्म करें",
        "pay_upi":                   "📲 UPI / GPay / PhonePe से पेमेंट करें",
        "pay_cod":                   "💵 कैश ऑन डिलीवरी (COD)",
        "order_placed":              "🎉 *ऑर्डर हो गया!*\n\nआपका ऑर्डर *{order_ref}* मिल गया।",
        "cod_instructions":          "💵 *कैश ऑन डिलीवरी*\n\nडिलीवरी पर *₹{total}* तैयार रखें।",
        "no_products":               "🛍 अभी कोई प्रोडक्ट उपलब्ध नहीं है।",
        "shop_not_found":            "❌ शॉप नहीं मिली। सही लिंक इस्तेमाल करें।",
        "shop_closed":               "🕐 *{shop_name}* अभी बंद है।\n\nखुलने का समय: *{open_time}* से *{close_time}*",
        "use_shop_link":             "कृपया शॉप लिंक से शुरू करें।",
        "order_confirmed_customer":  "🎉 *आपका ऑर्डर कन्फर्म हो गया!*\n\nहम आपकी डिलीवरी तैयार कर रहे हैं।",
        "order_cancelled_customer":  "❌ *आपका ऑर्डर रद्द हो गया।*\n\nअधिक जानकारी के लिए शॉप से संपर्क करें।",
        "order_delivered_customer":  "🎉 *आपका ऑर्डर डिलीवर हो गया!*\n\nऑर्डर करने के लिए धन्यवाद!",
        "my_orders_header":          "📦 *आपके ऑर्डर:*\n\n",
        "no_orders":                 "📦 *अभी कोई ऑर्डर नहीं है!*\n\nपहला ऑर्डर दें 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ चेकआउट रद्द करें",
        "checkout_cancelled":        "❌ चेकआउट रद्द हुआ।\n\nकार्ट सुरक्षित है!",
        "back_to_menu":              "🏠 मेनू",
        "back_to_cart":              "🛒 कार्ट पर वापस",
        "start_shopping":            "🛍 खरीदारी शुरू करें",
        "rate_product":              "*{product_name}* कैसा लगा?\nरेटिंग दें 👇",
        "review_thanks":             "रेटिंग के लिए धन्यवाद! 🙏",
        "choose_language":           "🌐 *भाषा चुनें:*",
        "language_set":              "✅ भाषा हिंदी में सेट हो गई!",
        "session_expired":           "⚠️ सेशन समाप्त हो गया। शॉप लिंक दोबारा खोलें।",
        "out_of_stock":              "❌ स्टॉक में नहीं है।",
        "only_left":                 "⚠️ सिर्फ {stock} बचे हैं!",
        "notify_me":                 "🔔 सूचित करें",
        "notify_contact":            "सूचना के लिए शॉप से संपर्क करें 📞: {contact}",
        "reorder_ready":             "🔄 *दोबारा ऑर्डर तैयार है!*",
        "order_more":                "🛍 और ऑर्डर करें",
        "track_order":               "📦 ऑर्डर ट्रैक करें",
        "welcome_back_cart":         "👋 वापस आए! आपकी कार्ट में *{n} {word}* हैं 🛒",
        "change_language":           "🌐 भाषा",
    },

    # ─────────────────────────────
    # TELUGU — తెలుగు
    # ─────────────────────────────
    "telugu": {
        "welcome":                   "🙏 *{shop_name}* కి స్వాగతం!",
        "browse":                    "🛍 ప్రొడక్ట్స్ చూడండి",
        "cart":                      "🛒 నా కార్ట్",
        "my_orders":                 "📦 నా ఆర్డర్లు",
        "about":                     "ℹ️ షాప్ గురించి",
        "contact":                   "📞 సంప్రదించండి",
        "empty_cart":                "మీ కార్ట్ ఖాళీగా ఉంది.",
        "added_to_cart":             "✅ {product_name} కార్ట్‌కి జోడించబడింది!",
        "cart_summary":              "🛒 *మీ కార్ట్:*\n\n{items}\n\n*మొత్తం: ₹{total}*",
        "checkout":                  "✅ చెక్అవుట్",
        "clear_cart":                "🗑 కార్ట్ క్లియర్ చేయండి",
        "cart_cleared":              "🗑 కార్ట్ క్లియర్ చేయబడింది!",
        "enter_address":             "📍 *దశ 1/3* — డెలివరీ చిరునామా నమోదు చేయండి:\n\n_ఉదా: ఫ్లాట్ 203, గ్రీన్ అపార్ట్‌మెంట్స్, కొండాపూర్_",
        "enter_phone":               "📱 *దశ 2/3* — మీ ఫోన్ నంబర్ నమోదు చేయండి:",
        "enter_delivery_date":       "🗓 *దశ 3/3* — డెలివరీ ఎప్పుడు కావాలి?\n\n_టైప్ చేయండి: ఈరోజు / రేపు / జల్దీ / 1 మార్చి_",
        "invalid_address":           "⚠️ పూర్తి చిరునామా నమోదు చేయండి (కనీసం 15 అక్షరాలు):",
        "invalid_phone":             "⚠️ సరైన భారతీయ మొబైల్ నంబర్ నమోదు చేయండి (6-9తో మొదలవాలి):",
        "invalid_date":              "⚠️ ఆ తేదీ గడిచిపోయింది. భవిష్యత్ తేదీ నమోదు చేయండి:",
        "order_summary":             "📋 *ఆర్డర్ సారాంశం*\n\n{items}\n*మొత్తం: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 డెలివరీ: {delivery_date}",
        "confirm_order":             "✅ ఆర్డర్ నిర్ధారించండి",
        "pay_upi":                   "📲 UPI / GPay / PhonePe ద్వారా చెల్లించండి",
        "pay_cod":                   "💵 క్యాష్ ఆన్ డెలివరీ (COD)",
        "order_placed":              "🎉 *ఆర్డర్ చేయబడింది!*\n\nమీ ఆర్డర్ *{order_ref}* అందుకోబడింది.",
        "cod_instructions":          "💵 *క్యాష్ ఆన్ డెలివరీ*\n\nడెలివరీ సమయంలో *₹{total}* సిద్ధంగా ఉంచండి.",
        "no_products":               "🛍 ప్రస్తుతం ఉత్పత్తులు అందుబాటులో లేవు.",
        "shop_not_found":            "❌ షాప్ కనుగొనబడలేదు. సరైన లింక్ ఉపయోగించండి.",
        "shop_closed":               "🕐 *{shop_name}* ఇప్పుడు మూసివేయబడింది.\n\nతెరవు సమయం: *{open_time}* నుండి *{close_time}*",
        "use_shop_link":             "షాప్ లింక్ ఉపయోగించి ప్రారంభించండి.",
        "order_confirmed_customer":  "🎉 *మీ ఆర్డర్ నిర్ధారించబడింది!*\n\nమీ అభ్యర్థించిన తేదీకి మేము సిద్ధం అవుతున్నాము.",
        "order_cancelled_customer":  "❌ *మీ ఆర్డర్ రద్దు చేయబడింది.*\n\nమరిన్ని వివరాలకు షాప్‌ని సంప్రదించండి.",
        "order_delivered_customer":  "🎉 *మీ ఆర్డర్ డెలివరీ చేయబడింది!*\n\nఆర్డర్ చేసినందుకు ధన్యవాదాలు!",
        "my_orders_header":          "📦 *మీ ఆర్డర్లు:*\n\n",
        "no_orders":                 "📦 *ఇంకా ఆర్డర్లు లేవు!*\n\nమొదటి ఆర్డర్ చేయండి 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ చెక్అవుట్ రద్దు చేయండి",
        "checkout_cancelled":        "❌ చెక్అవుట్ రద్దు చేయబడింది.\n\nకార్ట్ సేవ్ చేయబడింది!",
        "back_to_menu":              "🏠 మెనూ",
        "back_to_cart":              "🛒 కార్ట్‌కి తిరిగి వెళ్ళండి",
        "start_shopping":            "🛍 షాపింగ్ ప్రారంభించండి",
        "rate_product":              "*{product_name}* ఎలా ఉంది?\nరేటింగ్ ఇవ్వండి 👇",
        "review_thanks":             "రేటింగ్ ఇచ్చినందుకు ధన్యవాదాలు! 🙏",
        "choose_language":           "🌐 *భాష ఎంచుకోండి:*",
        "language_set":              "✅ భాష తెలుగులో సెట్ చేయబడింది!",
        "session_expired":           "⚠️ సెషన్ ముగిసింది. మీ షాప్ లింక్ మళ్ళీ తెరవండి.",
        "out_of_stock":              "❌ స్టాక్ లేదు.",
        "only_left":                 "⚠️ కేవలం {stock} మాత్రమే మిగిలాయి!",
        "notify_me":                 "🔔 నాకు తెలియజేయండి",
        "notify_contact":            "తెలియజేయడానికి షాప్‌ని సంప్రదించండి 📞: {contact}",
        "reorder_ready":             "🔄 *మళ్ళీ ఆర్డర్ సిద్ధంగా ఉంది!*",
        "order_more":                "🛍 మరిన్ని ఆర్డర్ చేయండి",
        "track_order":               "📦 ఆర్డర్ ట్రాక్ చేయండి",
        "welcome_back_cart":         "👋 తిరిగి వచ్చారు! మీ కార్ట్‌లో *{n} {word}* ఉన్నాయి 🛒",
        "change_language":           "🌐 భాష",
    },

    # ─────────────────────────────
    # KANNADA — ಕನ್ನಡ
    # ─────────────────────────────
    "kannada": {
        "welcome":                   "🙏 *{shop_name}* ಗೆ ಸ್ವಾಗತ!",
        "browse":                    "🛍 ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ",
        "cart":                      "🛒 ನನ್ನ ಕಾರ್ಟ್",
        "my_orders":                 "📦 ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
        "about":                     "ℹ️ ಅಂಗಡಿ ಬಗ್ಗೆ",
        "contact":                   "📞 ಸಂಪರ್ಕಿಸಿ",
        "empty_cart":                "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ.",
        "added_to_cart":             "✅ {product_name} ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ!",
        "cart_summary":              "🛒 *ನಿಮ್ಮ ಕಾರ್ಟ್:*\n\n{items}\n\n*ಒಟ್ಟು: ₹{total}*",
        "checkout":                  "✅ ಚೆಕ್‌ಔಟ್",
        "clear_cart":                "🗑 ಕಾರ್ಟ್ ತೆರವುಗೊಳಿಸಿ",
        "cart_cleared":              "🗑 ಕಾರ್ಟ್ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ!",
        "enter_address":             "📍 *ಹಂತ 1/3* — ವಿತರಣಾ ವಿಳಾಸ ನಮೂದಿಸಿ:\n\n_ಉದಾ: ಫ್ಲ್ಯಾಟ್ 203, ಗ್ರೀನ್ ಅಪಾರ್ಟ್‌ಮೆಂಟ್ಸ್, ಕೊಂಡಾಪುರ_",
        "enter_phone":               "📱 *ಹಂತ 2/3* — ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ:",
        "enter_delivery_date":       "🗓 *ಹಂತ 3/3* — ವಿತರಣೆ ಯಾವಾಗ ಬೇಕು?\n\n_ಟೈಪ್ ಮಾಡಿ: ನಾಳೆ, ತುರ್ತು, ಅಥವಾ ದಿನಾಂಕ_",
        "invalid_address":           "⚠️ ಸಂಪೂರ್ಣ ವಿಳಾಸ ನಮೂದಿಸಿ (ಕನಿಷ್ಠ 15 ಅಕ್ಷರಗಳು):",
        "invalid_phone":             "⚠️ ಸರಿಯಾದ ಭಾರತೀಯ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ (6-9 ರಿಂದ ಪ್ರಾರಂಭ):",
        "invalid_date":              "⚠️ ಆ ದಿನಾಂಕ ಮುಗಿದಿದೆ. ಭವಿಷ್ಯದ ದಿನಾಂಕ ನಮೂದಿಸಿ:",
        "order_summary":             "📋 *ಆರ್ಡರ್ ಸಾರಾಂಶ*\n\n{items}\n*ಒಟ್ಟು: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 ವಿತರಣೆ: {delivery_date}",
        "confirm_order":             "✅ ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ",
        "pay_upi":                   "📲 UPI / GPay / PhonePe ಮೂಲಕ ಪಾವತಿಸಿ",
        "pay_cod":                   "💵 ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ (COD)",
        "order_placed":              "🎉 *ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ!*\n\nನಿಮ್ಮ ಆರ್ಡರ್ *{order_ref}* ಸ್ವೀಕರಿಸಲಾಗಿದೆ.",
        "cod_instructions":          "💵 *ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ*\n\nವಿತರಣೆ ಸಮಯದಲ್ಲಿ *₹{total}* ಸಿದ್ಧಪಡಿಸಿ.",
        "no_products":               "🛍 ಪ್ರಸ್ತುತ ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಲಭ್ಯವಿಲ್ಲ.",
        "shop_not_found":            "❌ ಅಂಗಡಿ ಕಂಡುಬಂದಿಲ್ಲ. ಸರಿಯಾದ ಲಿಂಕ್ ಬಳಸಿ.",
        "shop_closed":               "🕐 *{shop_name}* ಈಗ ಮುಚ್ಚಿದೆ.\n\nತೆರೆಯುವ ಸಮಯ: *{open_time}* ರಿಂದ *{close_time}*",
        "use_shop_link":             "ಪ್ರಾರಂಭಿಸಲು ಅಂಗಡಿ ಲಿಂಕ್ ಬಳಸಿ.",
        "order_confirmed_customer":  "🎉 *ನಿಮ್ಮ ಆರ್ಡರ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ!*\n\nನಿಮ್ಮ ದಿನಾಂಕಕ್ಕೆ ತಯಾರಿ ಮಾಡುತ್ತಿದ್ದೇವೆ.",
        "order_cancelled_customer":  "❌ *ನಿಮ್ಮ ಆರ್ಡರ್ ರದ್ದಾಗಿದೆ.*\n\nಹೆಚ್ಚಿನ ಮಾಹಿತಿಗೆ ಅಂಗಡಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "order_delivered_customer":  "🎉 *ನಿಮ್ಮ ಆರ್ಡರ್ ವಿತರಿಸಲಾಗಿದೆ!*\n\nಆರ್ಡರ್ ಮಾಡಿದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!",
        "my_orders_header":          "📦 *ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು:*\n\n",
        "no_orders":                 "📦 *ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ!*\n\nಮೊದಲ ಆರ್ಡರ್ ನೀಡಿ 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ ಚೆಕ್‌ಔಟ್ ರದ್ದುಮಾಡಿ",
        "checkout_cancelled":        "❌ ಚೆಕ್‌ಔಟ್ ರದ್ದಾಗಿದೆ.\n\nಕಾರ್ಟ್ ಉಳಿಸಲಾಗಿದೆ!",
        "back_to_menu":              "🏠 ಮೆನು",
        "back_to_cart":              "🛒 ಕಾರ್ಟ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        "start_shopping":            "🛍 ಶಾಪಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
        "rate_product":              "*{product_name}* ಹೇಗಿತ್ತು?\nರೇಟಿಂಗ್ ನೀಡಿ 👇",
        "review_thanks":             "ರೇಟಿಂಗ್ ನೀಡಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದಗಳು! 🙏",
        "choose_language":           "🌐 *ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ:*",
        "language_set":              "✅ ಭಾಷೆ ಕನ್ನಡಕ್ಕೆ ಹೊಂದಿಸಲಾಗಿದೆ!",
        "session_expired":           "⚠️ ಸೆಷನ್ ಮುಗಿದಿದೆ. ನಿಮ್ಮ ಅಂಗಡಿ ಲಿಂಕ್ ಮತ್ತೆ ತೆರೆಯಿರಿ.",
        "out_of_stock":              "❌ ಸ್ಟಾಕ್ ಇಲ್ಲ.",
        "only_left":                 "⚠️ ಕೇವಲ {stock} ಮಾತ್ರ ಉಳಿದಿದೆ!",
        "notify_me":                 "🔔 ನನಗೆ ತಿಳಿಸಿ",
        "notify_contact":            "ತಿಳಿಸಲು ಅಂಗಡಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ 📞: {contact}",
        "reorder_ready":             "🔄 *ಮರು ಆರ್ಡರ್ ಸಿದ್ಧ!*",
        "order_more":                "🛍 ಇನ್ನಷ್ಟು ಆರ್ಡರ್ ಮಾಡಿ",
        "track_order":               "📦 ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
        "welcome_back_cart":         "👋 ಮರಳಿ ಬಂದಿರಿ! ನಿಮ್ಮ ಕಾರ್ಟ್‌ನಲ್ಲಿ *{n} {word}* ಇದೆ 🛒",
        "change_language":           "🌐 ಭಾಷೆ",
    },

    # ─────────────────────────────
    # TAMIL — தமிழ்
    # ─────────────────────────────
    "tamil": {
        "welcome":                   "🙏 *{shop_name}* க்கு வரவேற்கிறோம்!",
        "browse":                    "🛍 பொருட்களை பார்க்க",
        "cart":                      "🛒 என் கார்ட்",
        "my_orders":                 "📦 என் ஆர்டர்கள்",
        "about":                     "ℹ️ கடை பற்றி",
        "contact":                   "📞 தொடர்பு கொள்ள",
        "empty_cart":                "உங்கள் கார்ட் காலியாக உள்ளது.",
        "added_to_cart":             "✅ {product_name} கார்ட்டில் சேர்க்கப்பட்டது!",
        "cart_summary":              "🛒 *உங்கள் கார்ட்:*\n\n{items}\n\n*மொத்தம்: ₹{total}*",
        "checkout":                  "✅ செக்அவுட்",
        "clear_cart":                "🗑 கார்ட் அழிக்க",
        "cart_cleared":              "🗑 கார்ட் அழிக்கப்பட்டது!",
        "enter_address":             "📍 *படி 1/3* — டெலிவரி முகவரி உள்ளிடவும்:\n\n_எ.கா: ஃப்ளாட் 203, கிரீன் அப்பார்ட்மெண்ட்ஸ், கொண்டாபூர்_",
        "enter_phone":               "📱 *படி 2/3* — உங்கள் தொலைபேசி எண் உள்ளிடவும்:",
        "enter_delivery_date":       "🗓 *படி 3/3* — டெலிவரி எப்போது வேண்டும்?\n\n_டைப் செய்யுங்கள்: நாளை, அவசரம், அல்லது தேதி_",
        "invalid_address":           "⚠️ முழுமையான முகவரி உள்ளிடவும் (குறைந்தது 15 எழுத்துகள்):",
        "invalid_phone":             "⚠️ சரியான இந்திய மொபைல் எண் உள்ளிடவும் (6-9 இல் தொடங்க வேண்டும்):",
        "invalid_date":              "⚠️ அந்த தேதி கடந்துவிட்டது. எதிர்கால தேதி உள்ளிடவும்:",
        "order_summary":             "📋 *ஆர்டர் சுருக்கம்*\n\n{items}\n*மொத்தம்: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 டெலிவரி: {delivery_date}",
        "confirm_order":             "✅ ஆர்டரை உறுதிப்படுத்தவும்",
        "pay_upi":                   "📲 UPI / GPay / PhonePe மூலம் செலுத்தவும்",
        "pay_cod":                   "💵 கேஷ் ஆன் டெலிவரி (COD)",
        "order_placed":              "🎉 *ஆர்டர் செய்யப்பட்டது!*\n\nஉங்கள் ஆர்டர் *{order_ref}* பெறப்பட்டது.",
        "cod_instructions":          "💵 *கேஷ் ஆன் டெலிவரி*\n\nடெலிவரி நேரத்தில் *₹{total}* தயாராக வைத்திருங்கள்.",
        "no_products":               "🛍 தற்போது பொருட்கள் எதுவும் இல்லை.",
        "shop_not_found":            "❌ கடை கிடைக்கவில்லை. சரியான லிங்க் பயன்படுத்தவும்.",
        "shop_closed":               "🕐 *{shop_name}* இப்போது மூடியுள்ளது.\n\nதிறக்கும் நேரம்: *{open_time}* முதல் *{close_time}*",
        "use_shop_link":             "தொடங்க கடை லிங்கை பயன்படுத்தவும்.",
        "order_confirmed_customer":  "🎉 *உங்கள் ஆர்டர் உறுதிப்படுத்தப்பட்டது!*\n\nகோரிய தேதிக்கு தயார் செய்கிறோம்.",
        "order_cancelled_customer":  "❌ *உங்கள் ஆர்டர் ரத்து செய்யப்பட்டது.*\n\nமேலும் தகவலுக்கு கடையை தொடர்பு கொள்ளவும்.",
        "order_delivered_customer":  "🎉 *உங்கள் ஆர்டர் டெலிவரி செய்யப்பட்டது!*\n\nஆர்டர் செய்தமைக்கு நன்றி!",
        "my_orders_header":          "📦 *உங்கள் ஆர்டர்கள்:*\n\n",
        "no_orders":                 "📦 *இன்னும் ஆர்டர்கள் இல்லை!*\n\nமுதல் ஆர்டர் செய்யுங்கள் 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ செக்அவுட் ரத்து செய்யவும்",
        "checkout_cancelled":        "❌ செக்அவுட் ரத்து செய்யப்பட்டது.\n\nகார்ட் சேமிக்கப்பட்டுள்ளது!",
        "back_to_menu":              "🏠 மெனு",
        "back_to_cart":              "🛒 கார்ட்டிற்கு திரும்பவும்",
        "start_shopping":            "🛍 ஷாப்பிங் தொடங்கவும்",
        "rate_product":              "*{product_name}* எப்படி இருந்தது?\nரேட்டிங் கொடுங்கள் 👇",
        "review_thanks":             "ரேட்டிங் கொடுத்தமைக்கு நன்றி! 🙏",
        "choose_language":           "🌐 *மொழியை தேர்வு செய்யுங்கள்:*",
        "language_set":              "✅ மொழி தமிழிற்கு அமைக்கப்பட்டது!",
        "session_expired":           "⚠️ அமர்வு முடிந்தது. உங்கள் கடை லிங்கை மீண்டும் திறக்கவும்.",
        "out_of_stock":              "❌ ஸ்டாக் இல்லை.",
        "only_left":                 "⚠️ {stock} மட்டுமே மீதம்!",
        "notify_me":                 "🔔 எனக்கு தெரிவிக்கவும்",
        "notify_contact":            "தெரிவிக்க கடையை தொடர்பு கொள்ளவும் 📞: {contact}",
        "reorder_ready":             "🔄 *மீண்டும் ஆர்டர் தயார்!*",
        "order_more":                "🛍 மேலும் ஆர்டர் செய்யவும்",
        "track_order":               "📦 ஆர்டரை கண்காணிக்கவும்",
        "welcome_back_cart":         "👋 மீண்டும் வரவேற்கிறோம்! கார்ட்டில் *{n} {word}* உள்ளது 🛒",
        "change_language":           "🌐 மொழி",
    },

    # ─────────────────────────────
    # MALAYALAM — മലയാളം
    # ─────────────────────────────
    "malayalam": {
        "welcome":                   "🙏 *{shop_name}* ലേക്ക് സ്വാഗതം!",
        "browse":                    "🛍 ഉൽപ്പന്നങ്ങൾ കാണുക",
        "cart":                      "🛒 എന്റെ കാർട്ട്",
        "my_orders":                 "📦 എന്റെ ഓർഡറുകൾ",
        "about":                     "ℹ️ കടയെക്കുറിച്ച്",
        "contact":                   "📞 ബന്ധപ്പെടുക",
        "empty_cart":                "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്.",
        "added_to_cart":             "✅ {product_name} കാർട്ടിൽ ചേർക്കപ്പെട്ടു!",
        "cart_summary":              "🛒 *നിങ്ങളുടെ കാർട്ട്:*\n\n{items}\n\n*ആകെ: ₹{total}*",
        "checkout":                  "✅ ചെക്ക്ഔട്ട്",
        "clear_cart":                "🗑 കാർട്ട് മായ്ക്കുക",
        "cart_cleared":              "🗑 കാർട്ട് മായ്ക്കപ്പെട്ടു!",
        "enter_address":             "📍 *ഘട്ടം 1/3* — ഡെലിവറി വിലാസം നൽകുക:\n\n_ഉദാ: ഫ്ലാറ്റ് 203, ഗ്രീൻ അപ്പാർട്ട്‌മെന്റ്, കൊണ്ടാപൂർ_",
        "enter_phone":               "📱 *ഘട്ടം 2/3* — നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക:",
        "enter_delivery_date":       "🗓 *ഘട്ടം 3/3* — ഡെലിവറി എന്ന് വേണം?\n\n_ടൈപ്പ് ചെയ്യുക: നാളെ, അടിയന്തരം, അല്ലെങ്കിൽ തീയതി_",
        "invalid_address":           "⚠️ പൂർണ്ണ വിലാസം നൽകുക (കുറഞ്ഞത് 15 അക്ഷരങ്ങൾ):",
        "invalid_phone":             "⚠️ ശരിയായ ഇന്ത്യൻ മൊബൈൽ നമ്പർ നൽകുക (6-9 ൽ ആരംഭിക്കണം):",
        "invalid_date":              "⚠️ ആ തീയതി കഴിഞ്ഞുപോയി. ഭാവി തീയതി നൽകുക:",
        "order_summary":             "📋 *ഓർഡർ സംഗ്രഹം*\n\n{items}\n*ആകെ: ₹{total}*\n📍 {address}\n📱 {phone}\n🗓 ഡെലിവറി: {delivery_date}",
        "confirm_order":             "✅ ഓർഡർ സ്ഥിരീകരിക്കുക",
        "pay_upi":                   "📲 UPI / GPay / PhonePe വഴി അടയ്ക്കുക",
        "pay_cod":                   "💵 ക്യാഷ് ഓൺ ഡെലിവറി (COD)",
        "order_placed":              "🎉 *ഓർഡർ നൽകി!*\n\nനിങ്ങളുടെ ഓർഡർ *{order_ref}* ലഭിച്ചു.",
        "cod_instructions":          "💵 *ക്യാഷ് ഓൺ ഡെലിവറി*\n\nഡെലിവറി സമയത്ത് *₹{total}* തയ്യാറാക്കി വയ്ക്കുക.",
        "no_products":               "🛍 ഇപ്പോൾ ഉൽപ്പന്നങ്ങളൊന്നും ലഭ്യമല്ല.",
        "shop_not_found":            "❌ കട കണ്ടെത്തിയില്ല. ശരിയായ ലിങ്ക് ഉപയോഗിക്കുക.",
        "shop_closed":               "🕐 *{shop_name}* ഇപ്പോൾ അടഞ്ഞിരിക്കുന്നു.\n\nതുറക്കൽ സമയം: *{open_time}* മുതൽ *{close_time}*",
        "use_shop_link":             "ആരംഭിക്കാൻ കട ലിങ്ക് ഉപയോഗിക്കുക.",
        "order_confirmed_customer":  "🎉 *നിങ്ങളുടെ ഓർഡർ സ്ഥിരീകരിച്ചു!*\n\nആവശ്യപ്പെട്ട തീയതിയിലേക്ക് തയ്യാറാകുന്നു.",
        "order_cancelled_customer":  "❌ *നിങ്ങളുടെ ഓർഡർ റദ്ദ് ചെയ്തു.*\n\nകൂടുതൽ വിവരങ്ങൾക്ക് കടയുമായി ബന്ധപ്പെടുക.",
        "order_delivered_customer":  "🎉 *നിങ്ങളുടെ ഓർഡർ ഡെലിവർ ചെയ്തു!*\n\nഓർഡർ ചെയ്തതിന് നന്ദി!",
        "my_orders_header":          "📦 *നിങ്ങളുടെ ഓർഡറുകൾ:*\n\n",
        "no_orders":                 "📦 *ഇതുവരെ ഓർഡറുകളൊന്നുമില്ല!*\n\nആദ്യ ഓർഡർ നൽകൂ 😊",
        "order_line":                "• {items} — ₹{total} — *{status}*\n",
        "cancel_checkout":           "❌ ചെക്ക്ഔട്ട് റദ്ദ് ചെയ്യുക",
        "checkout_cancelled":        "❌ ചെക്ക്ഔട്ട് റദ്ദ് ചെയ്തു.\n\nകാർട്ട് സേവ് ചെയ്തിരിക്കുന്നു!",
        "back_to_menu":              "🏠 മെനു",
        "back_to_cart":              "🛒 കാർട്ടിലേക്ക് മടങ്ങുക",
        "start_shopping":            "🛍 ഷോപ്പിംഗ് ആരംഭിക്കുക",
        "rate_product":              "*{product_name}* എങ്ങനെ ഉണ്ടായിരുന്നു?\nറേറ്റിംഗ് നൽകൂ 👇",
        "review_thanks":             "റേറ്റിംഗ് നൽകിയതിന് നന്ദി! 🙏",
        "choose_language":           "🌐 *ഭാഷ തിരഞ്ഞെടുക്കുക:*",
        "language_set":              "✅ ഭാഷ മലയാളത്തിലേക്ക് സജ്ജമാക്കി!",
        "session_expired":           "⚠️ സെഷൻ കഴിഞ്ഞു. നിങ്ങളുടെ ഷോപ്പ് ലിങ്ക് വീണ്ടും തുറക്കുക.",
        "out_of_stock":              "❌ സ്റ്റോക്ക് ഇല്ല.",
        "only_left":                 "⚠️ {stock} മാത്രം ബാക്കിയുണ്ട്!",
        "notify_me":                 "🔔 എന്നെ അറിയിക്കുക",
        "notify_contact":            "അറിയിക്കാൻ കടയുമായി ബന്ധപ്പെടുക 📞: {contact}",
        "reorder_ready":             "🔄 *വീണ്ടും ഓർഡർ തയ്യാർ!*",
        "order_more":                "🛍 കൂടുതൽ ഓർഡർ ചെയ്യുക",
        "track_order":               "📦 ഓർഡർ ട്രാക്ക് ചെയ്യുക",
        "welcome_back_cart":         "👋 തിരിച്ചു വന്നു! കാർട്ടിൽ *{n} {word}* ഉണ്ട് 🛒",
        "change_language":           "🌐 ഭാഷ",
    },
}


# ─────────────────────────────────────────────────────
# TRANSLATE HELPER
# ─────────────────────────────────────────────────────

def t(language, key, **kwargs):
    """
    Get a translated string for the given language and key.
    Falls back to English if key missing in that language.
    Usage: t("telugu", "welcome", shop_name="Priya Cakes")
    """
    lang_strings = STRINGS.get(language, STRINGS["english"])
    template = lang_strings.get(key) or STRINGS["english"].get(key, key)
    try:
        return template.format(**kwargs)
    except KeyError:
        return template


# ─────────────────────────────────────────────────────
# LANGUAGE PICKER KEYBOARD
# ─────────────────────────────────────────────────────

LANGUAGE_OPTIONS = [
    ("🇬🇧 English",   "english"),
    ("🇮🇳 हिंदी",      "hindi"),
    ("తెలుగు",        "telugu"),
    ("ಕನ್ನಡ",         "kannada"),
    ("தமிழ்",         "tamil"),
    ("മലയാളം",       "malayalam"),
]

def language_picker_keyboard():
    """
    Returns an InlineKeyboardMarkup with all 6 language buttons.
    Each button sends callback_data like: lang_telugu
    """
    from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton
    m = InlineKeyboardMarkup(row_width=2)
    buttons = [
        InlineKeyboardButton(label, callback_data=f"lang_{code}")
        for label, code in LANGUAGE_OPTIONS
    ]
    m.add(*buttons)
    return m